networks:
  project_net:
    driver: bridge
  # infra_net:
  # external: true
  infra_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.19.0.0/16

include:
  - Django/docker-compose.yml
  - FastAPI/docker-compose.yml
