name: ksql
services:
  ksqldb-server:
    image: confluentinc/cp-ksqldb-server:8.0.3
    hostname: ksqldb-server
    container_name: ksqldb-server
    ports:
      - "${KSQLDB_HOST_PORT}:${KSQLDB_PORT}"
    environment:
      KSQL_CONFIG_DIR: "/etc/ksql"
      KSQL_BOOTSTRAP_SERVERS: "kafka-1:${KAFKA_INTERNAL_PORT},kafka-2:${KAFKA_INTERNAL_PORT},kafka-3:${KAFKA_INTERNAL_PORT}"
      KSQL_HOST_NAME: ksqldb-server
      KSQL_LISTENERS: "http://0.0.0.0:${KSQLDB_PORT}"
      KSQL_CACHE_MAX_BYTES_BUFFERING: 0
      KSQL_KSQL_SCHEMA_REGISTRY_URL: "http://schema-registry:${SCHEMA_REGISTRY_PORT}"
      KSQL_PRODUCER_INTERCEPTOR_CLASSES: "io.confluent.monitoring.clients.interceptor.MonitoringProducerInterceptor"
      KSQL_CONSUMER_INTERCEPTOR_CLASSES: "io.confluent.monitoring.clients.interceptor.MonitoringConsumerInterceptor"
      KSQL_KSQL_CONNECT_URL: "http://kafka-connect:${KAFKA_CONNECT_PORT}"
      KSQL_KSQL_LOGGING_PROCESSING_TOPIC_REPLICATION_FACTOR: 1
      KSQL_KSQL_LOGGING_PROCESSING_TOPIC_AUTO_CREATE: "true"
      KSQL_KSQL_LOGGING_PROCESSING_STREAM_AUTO_CREATE: "true"
    volumes:
      - ksqldb-data-volume:/var/lib/ksql
    networks:
      - infra_net
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "2"

  ksqldb-cli:
    image: confluentinc/cp-ksqldb-cli:8.0.3
    container_name: ksqldb-cli
    depends_on:
      - ksqldb-server
    entrypoint: /bin/sh
    tty: true
    networks:
      - infra_net
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "2"

  ksql-datagen:
    image: confluentinc/ksqldb-examples:8.0.3
    hostname: ksql-datagen
    container_name: ksql-datagen
    command: "bash -c 'echo Waiting for Kafka to be ready... && \
      cub kafka-ready -b kafka-1:${KAFKA_INTERNAL_PORT} 1 40 && \
      echo Waiting for Confluent Schema Registry to be ready... && \
      cub sr-ready schema-registry ${SCHEMA_REGISTRY_PORT} 40 && \
      echo Waiting a few seconds for topic creation to finish... && \
      sleep 11 && \
      tail -f /dev/null'"
    environment:
      KSQL_CONFIG_DIR: "/etc/ksql"
      STREAMS_BOOTSTRAP_SERVERS: kafka-1:${KAFKA_INTERNAL_PORT},kafka-2:${KAFKA_INTERNAL_PORT},kafka-3:${KAFKA_INTERNAL_PORT}
      STREAMS_SCHEMA_REGISTRY_HOST: schema-registry
      STREAMS_SCHEMA_REGISTRY_PORT: ${SCHEMA_REGISTRY_PORT}
    networks:
      - infra_net
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "2"

volumes:
  ksqldb-data-volume:

networks:
  infra_net:
    name: infra_net
    driver: bridge
    ipam:
      config:
        - subnet: ${INFRA_SUBNET:-172.19.0.0/16}
          gateway: ${INFRA_GATEWAY:-172.19.0.1}
