name: syncthing

volumes:
  syncthing-volume:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${DEFAULT_TOOLING_DIR}/syncthing
  resources-contents-volume:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${DEFAULT_RESOURCES_DIR}

services:
  syncthing:
    extends:
      file: ../../common-optimizations.yml
      service: template-infra-med
    image: syncthing/syncthing:2.0.13
    container_name: syncthing
    ports:
      - ${SYNCTHING_SYNC_HOST_PORT:-22000}:${SYNCTHING_SYNC_PORT:-22000}/tcp
      - ${SYNCTHING_SYNC_HOST_PORT:-22000}:${SYNCTHING_SYNC_PORT:-22000}/udp
      - ${SYNCTHING_BROADCASTS_HOST_PORT:-21027}:${SYNCTHING_BROADCASTS_PORT:-21027}/udp
      # - ${SYNCTHING_GUI_PORT}:${SYNCTHING_GUI_PORT}
    expose:
      - ${SYNCTHING_GUI_PORT:-8384}
    environment:
      - PUID=1000
      - PGID=1000

      - FILE__USER=${SYNCTHING_USERNAME}
      - FILE__PASSWORD_FILE=/run/secrets/syncthing_password
    secrets:
      - syncthing_password
    volumes:
      - syncthing-volume:/var/syncthing:rw
      - resources-contents-volume:/Sync:rw
    healthcheck:
      test:
        [
          'CMD-SHELL',
          'curl -fkLsS -m 2 syncthing:8384/rest/noauth/health | grep -o --color=never OK || exit 1',
        ]
      interval: 15s
      timeout: 30s
      retries: 5
      start_period: 30s
    labels:
      traefik.enable: 'true'
      traefik.http.routers.syncthing.rule: Host(`syncthing.${DEFAULT_URL}`)
      traefik.http.routers.syncthing.entrypoints: websecure
      traefik.http.routers.syncthing.tls: 'true'
      traefik.http.services.syncthing.loadbalancer.server.port: ${SYNCTHING_GUI_PORT:-8384}

    networks:
      - nt-sync
      - nt-webserver
      - nt-observability

secrets:
  syncthing_password:
    external: true
