x-common:
  security: &security { security_opt: [no-new-privileges:true], cap_drop: [ALL] }
  logging: &logging { driver: 'json-file', options: { max-size: '5m', max-file: '2' } }
  res-low: &res-low { deploy: { resources: { limits: { cpus: '0.2', memory: 128M }, reservations: { memory: 64M } } } }
  res-med: &res-med { deploy: { resources: { limits: { cpus: '0.5', memory: 512M }, reservations: { memory: 256M } } } }
  res-high: &res-high { deploy: { resources: { limits: { cpus: '1.0', memory: 1G }, reservations: { memory: 512M } } } }
  restart: &restart { restart: unless-stopped }
  labels-base: &labels-base { traefik.enable: 'true', hy-home.managed: 'true' }

x-logging: &default-logging
volumes:
  syncthing-volume:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${DEFAULT_TOOLING_DIR}/syncthing
  resources-contents-volume:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${DEFAULT_RESOURCES_DIR}

services:
  syncthing:
    image: syncthing/syncthing:2.0.13
    restart: unless-stopped
    container_name: syncthing
    ports:
      - ${SYNCTHING_SYNC_HOST_PORT:-22000}:${SYNCTHING_SYNC_PORT:-22000}/tcp
      - ${SYNCTHING_SYNC_HOST_PORT:-22000}:${SYNCTHING_SYNC_PORT:-22000}/udp
      - ${SYNCTHING_BROADCASTS_HOST_PORT:-21027}:${SYNCTHING_BROADCASTS_PORT:-21027}/udp
      # - ${SYNCTHING_GUI_PORT}:${SYNCTHING_GUI_PORT}
    expose:
      - ${SYNCTHING_GUI_PORT:-8384}
    environment:
      - PUID=1000
      - PGID=1000

      - FILE__USER=${SYNCTHING_USERNAME}
      - FILE__PASSWORD_FILE=/run/secrets/syncthing_password
    secrets:
      - syncthing_password
    volumes:
      - syncthing-volume:/var/syncthing:rw
      - resources-contents-volume:/Sync:rw
    healthcheck:
      test:
        [
          'CMD-SHELL',
          'curl -fkLsS -m 2 syncthing:8384/rest/noauth/health | grep -o --color=never OK || exit 1',
        ]
      interval: 15s
      timeout: 30s
      retries: 5
      start_period: 30s
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    logging: *logging
    # labels:
    #   - traefik.enable=true
    #   - traefik.docker.network=nt-develop
    #   - traefik.http.services.syncthing.loadbalancer.server.port=8384
    #   - traefik.http.routers.syncthing.rule=Host(`syncthing.${DEFAULT_URL}`)
    #   - traefik.http.routers.syncthing.entrypoints=web
    #   # For https:
    #   - traefik.http.routers.syncthing-secure.rule=Host(`syncthing.${DEFAULT_URL}`)
    #   - traefik.http.routers.syncthing-secure.entrypoints=websecure
    #   - traefik.http.middlewares.web-redirect-websecure.redirectscheme.scheme=https
    #   - traefik.http.routers.syncthing.middlewares=web-redirect-websecure

    networks:
      - nt-sync
      - nt-webserver
      - nt-observability

secrets:
  syncthing_password:
    external: true
