_meta:
  type: 'internalusers'
  config_version: 2

# admin user
admin:
  hash: '$2y$12$fEqrJs26IUqu4BjztfsOy.ngX9DW0GudtLI0Nmtjx6t8oLIHP2.LS'
  reserved: true
  backend_roles:
    - 'admin'
  description: 'Administrator user'

# user for Dashboards
kibanaserver:
  hash: '$2y$12$Br4xYb4OgoKoWe9tDsVwXee3HfCTJgYMe8iSU3N/TyxyoEcRFl1R6'
  reserved: true
  description: 'Dashboards server user'

# user for Prometheus Exporter
exporter:
  hash: '$2y$12$n1GdisJt2X6i/8vIj3TQ2Oik2.q68IzzUkLCKbhN8VKV7IcJK2ueG'
  reserved: false
  backend_roles:
    - 'readall'
  description: 'Prometheus exporter user'
