_meta:
  type: "rolesmapping"
  config_version: 2

all_access:
  reserved: false
  backend_roles:
    - "admin"
    - "opensearch_admin"
    - "opensearch-admin"
  users:
    - "admin"

kibana_server:
  reserved: true
  users:
    - "kibanaserver"

readall:
  reserved: false
  backend_roles:
    - "user"
    - "readall"
    - "opensearch_readall"
    - "opensearch-readall"
  users: []

exporter_role:
  reserved: false
  users:
    - "exporter"
