name: locust

x-labels-base: &labels-base
  hy-home.managed: "true"
  hy-home.tier: tooling

volumes:
  locust-data:
    # driver: local
    # driver_opts:
    #   o: bind
    #   type: none
    #   device: ${DEFAULT_LOCUST_DIR}

services:
  locust-master:
    extends:
      file: ../../common-optimizations.yml
      service: template-infra-med
    build: .
    ports:
      - '${LOCUST_HOST_PORT:-18089}:${LOCUST_PORT:-8089}'
    environment:
      - LOCUST_INFLUXDB_HOST=influxdb
      - LOCUST_INFLUXDB_PORT=${INFLUXDB_PORT:-8086}
      - LOCUST_INFLUXDB_ORG=${INFLUXDB_ORG}
      - LOCUST_INFLUXDB_BUCKET=${INFLUXDB_BUCKET}
    volumes:
      - locust-data:/mnt/locust
    networks:
      - infra_net
    secrets:
      - influxdb_api_token
    command: >
      /bin/sh -c "
      export LOCUST_INFLUXDB_TOKEN=$$(cat /run/secrets/influxdb_api_token | tr -d '\n') &&
      exec locust -f /mnt/locust/locustfile.py --master
      "
    depends_on:
      influxdb:
        condition: service_healthy
    extra_hosts:
      - '${DEFAULT_URL}:host-gateway'

  locust-worker:
    extends:
      file: ../../common-optimizations.yml
      service: template-infra-med
    build: .
    environment:
      - LOCUST_INFLUXDB_HOST=influxdb
      - LOCUST_INFLUXDB_PORT=${INFLUXDB_PORT:-8086}
      - LOCUST_INFLUXDB_ORG=${INFLUXDB_ORG}
      - LOCUST_INFLUXDB_BUCKET=${INFLUXDB_BUCKET}
    volumes:
      - locust-data:/mnt/locust
    networks:
      - infra_net
    secrets:
      - influxdb_api_token
    command: >
      /bin/sh -c "
      export LOCUST_INFLUXDB_TOKEN=$$(cat /run/secrets/influxdb_api_token | tr -d '\n') &&
      exec locust -f /mnt/locust/locustfile.py --worker --master-host locust-master
      "
    depends_on:
      locust-master:
        condition: service_healthy
    deploy:
      replicas: 2 # 워커를 2개로 늘려서 부하 분산 (필요시 조절)
    extra_hosts:
      - '${DEFAULT_URL}:host-gateway'

secrets:
  influxdb_api_token:
    external: true
