name: nginx

volumes:
  nginx-logs:
  nginx_certs:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DEFAULT_DOCKER_PROJECT_PATH}/secrets/certs

services:
  nginx:
    extends:
      file: ../../common-optimizations.yml
      service: template-infra-low
    image: nginx:alpine
    container_name: nginx
    ports:
      - ${HTTP_HOST_PORT:-80}:${HTTP_PORT:-80}
      - ${HTTPS_HOST_PORT:-443}:${HTTPS_PORT:-443}
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
      - nginx_certs:/etc/nginx/certs:ro
    networks:
      - infra_net
    depends_on:
      minio: { condition: service_healthy }
    healthcheck:
      test: ['CMD-SHELL', 'wget -q --spider http://localhost:${HTTP_PORT:-80} || exit 1']
      interval: 15s
      timeout: 30s
      retries: 5
      start_period: 30s

networks:
  infra_net:
    name: infra_net
    external: true
