services:
  traefik:
    image: traefik:v3.6.2
    container_name: traefik
    hostname: traefik
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped    
    environment:
      - TZ=${DEFAULT_TIMEZONE}    
    ports:
      - ${TRAEFIK_HTTP_HOST_PORT}:${TRAEFIK_HTTP_PORT}
      - ${TRAEFIK_HTTPS_HOST_PORT}:${TRAEFIK_HTTPS_PORT}
      - ${TRAEFIK_DASHBOARD_HOST_PORT}:${TRAEFIK_DASHBOARD_PORT}
      - ${TRAEFIK_METRICS_HOST_PORT}:${TRAEFIK_METRICS_PORT}    
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./certs:/certs:ro
      - ./dynamic:/dynamic:ro      
    command:
      # EntryPoints
      - "--entrypoints.web.address=:${TRAEFIK_HTTP_PORT}"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--entrypoints.web.http.redirections.entrypoint.permanent=true"
      - "--entrypoints.websecure.address=:${TRAEFIK_HTTPS_PORT}"
      - "--entrypoints.websecure.http.tls=true"
      - "--serversTransport.rootCAs=/certs/rootCA.pem"
      # Attach the static configuration tls.yaml file that contains the tls configuration settings
      - "--providers.file.filename=/dynamic/tls.yaml"      

      # Providers 
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=infra_net"

      # API & Dashboard 
      - "--api.dashboard=true"
      - "--api.insecure=false"

      # Observability 
      - "--log.level=INFO"
      - "--accesslog=true"
      # If using a dedicated metrics entry point, define it:
      - "--ping=true"
      - "--ping.entrypoint=metrics"   # 이미 metrics entrypoint (:8082)를 정의해놨으니 이걸 사용
      - "--entrypoints.metrics.address=:8082"

      # ... other command arguments ...
      - "--metrics.prometheus=true"
      # Optionally change the entry point metrics are exposed on (defaults to 'traefik')
      - "--metrics.prometheus.entrypoint=metrics"
      # Add labels to metrics for routers/services (can increase cardinality)      
      - "--metrics.prometheus.addrouterslabels=true"
      - "--metrics.prometheus.addserviceslabels=true"
    labels:
      # Enable self‑routing
      - "traefik.enable=true"      

      # Dashboard router
      - "traefik.http.routers.dashboard.rule=Host(`dashboard.${DEFAULT_URL}`)"
      - "traefik.http.routers.dashboard.entrypoints=websecure"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.routers.dashboard.tls=true"

      # Basic‑auth middleware
      - "traefik.http.middlewares.dashboard-auth.basicauth.users=${TRAEFIK_BASICAUTH}"
      - "traefik.http.routers.dashboard.middlewares=dashboard-auth@docker"
    # healthcheck:
    #   test: ['CMD', 'traefik', 'healthcheck', '--ping']
    #   interval: 10s
    #   timeout: 10s
    #   retries: 30
    networks:
      infra_net:
        ipv4_address: 172.19.0.13  
    logging: 
      driver: 'json-file'
      options:
        max-size: '5m'
        max-file: '2'
  # whoami:
  #   image: traefik/whoami
  #   container_name: whoami
  #   restart: unless-stopped
  #   networks:
  #     - infra_net
  #   labels:
  #     - "traefik.enable=true"
  #     - "traefik.http.routers.whoami.rule=Host(`whoami.${DEFAULT_URL}`)"
  #     - "traefik.http.routers.whoami.entrypoints=websecure"
  #     - "traefik.http.routers.whoami.tls=true"