global:
  resolve_timeout: 5m
  # # [Email 공통 설정] Gmail 기준
  smtp_smarthost: "smtp.gmail.com:587"
  smtp_from: "alertmanager@example.com" # 발신자 표시용 (실제 계정과 달라도 됨)
  smtp_auth_username: "__SMTP_USERNAME__" # 본인 구글 계정
  smtp_auth_password: "__SMTP_PASSWORD__" # 구글 앱 비밀번호 (16자리)
  # smtp_require_tls: true

route:
  group_by: ["alertname", "job"]
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  # 기본적으로 모든 알림을 이 리시버로 보냅니다.
  receiver: "team-notifications"

receivers:
  - name: "team-notifications"
    # Slack 발송 설정
    slack_configs:
      - api_url: "__SLACK_WEBHOOK_URL__" # SLACK_WEBHOOK_URL로 치환
        channel: "#notification" # 메시지를 보낼 채널명 (Webhook 설정과 일치 권장)
        send_resolved: true
        icon_url: https://avatars3.githubusercontent.com/u/3380462
        title: '{{ template "slack.default.title" . }}'
        text: >-
          {{ range .Alerts -}}
            *Alert:* {{ .Annotations.summary }} - `{{ .Labels.severity }}`
            *Description:* {{ .Annotations.description }}
            *Time:* {{ .StartsAt.Format "2006-01-02 15:04:05" }}  *Description:*
          {{ .Annotations.description }}
            *Details:*
              {{ range .Labels.SortedPairs }} • *{{ .Name }}:* `{{ .Value }}`
              {{ end }}
          {{ end }}
